import type {PoolClient} from 'pg';
import type {SalesReturnInput} from '@erp/contracts';
import {formatDecimal,parseDecimal,roundHalfAwayFromZero} from '@erp/contracts';
import {HttpError} from '../../lib/http.js';
import {beginIdempotent,completeIdempotent} from '../../lib/idempotency.js';
import {nextDocumentNumber} from '../../lib/document-number.js';
import {receiveInventory} from '../inventory/service.js';
import {postJournal} from '../accounting/posting-service.js';
import {appendAuditEvent} from '../audit/routes.js';

export async function postSalesReturn(client:PoolClient,auth:Express.Request['auth']&{},invoiceId:string,key:string,input:SalesReturnInput){
 const attempt=await beginIdempotent(client,{companyId:auth.companyId,key,action:'sales_return.post',body:{invoiceId,...input}});if(attempt.kind==='replay')return attempt;
 const invoice=(await client.query<{id:string;customer_id:string|null;warehouse_id:string|null;total:string;returned_amount:string}>(`SELECT id,customer_id,warehouse_id,total,returned_amount FROM sales_invoices WHERE id=$1 AND company_id=$2 FOR UPDATE`,[invoiceId,auth.companyId])).rows[0];
 if(!invoice)throw new HttpError(404,'INVOICE_NOT_FOUND','Invoice not found');if(!invoice.warehouse_id)throw new HttpError(409,'INVOICE_WAREHOUSE_MISSING','Invoice has no stock warehouse');
 const ids=input.items.map(i=>i.invoiceItemId);const rows=await client.query<{id:string;product_id:string;quantity:string;returned_quantity:string;unit_price:string;cost_price:string;tax_rate:string}>(`SELECT id,product_id,quantity,returned_quantity,unit_price,cost_price,tax_rate FROM sales_invoice_items WHERE invoice_id=$1 AND id=ANY($2::uuid[]) FOR UPDATE`,[invoiceId,ids]);if(rows.rows.length!==ids.length)throw new HttpError(422,'INVALID_RETURN_ITEM','Return item does not belong to invoice');
 const byId=new Map(rows.rows.map(r=>[r.id,r]));const calc=input.items.map(requested=>{const row=byId.get(requested.invoiceItemId)!;const qty=parseDecimal(requested.quantity,3);if(parseDecimal(row.returned_quantity,3)+qty>parseDecimal(row.quantity,3))throw new HttpError(409,'EXCESS_RETURN','Return quantity exceeds eligible quantity');const base=roundHalfAwayFromZero(qty*parseDecimal(row.unit_price,2),1000n);const tax=roundHalfAwayFromZero(base*parseDecimal(row.tax_rate,4),1_000_000n);const cost=roundHalfAwayFromZero(qty*parseDecimal(row.cost_price,2),1000n);return{requested,row,base,tax,cost,total:base+tax};});
 const subtotal=calc.reduce((s,r)=>s+r.base,0n),tax=calc.reduce((s,r)=>s+r.tax,0n),total=subtotal+tax,cost=calc.reduce((s,r)=>s+r.cost,0n);const number=await nextDocumentNumber(client,{companyId:auth.companyId,documentType:'sales_return',prefix:'SR',businessDate:input.businessDate});
 const returned=await client.query<{id:string}>(`INSERT INTO sales_returns(company_id,return_number,invoice_id,customer_id,warehouse_id,business_date,reason,subtotal,tax_amount,total,operation_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,[auth.companyId,number,invoiceId,invoice.customer_id,invoice.warehouse_id,input.businessDate,input.reason,formatDecimal(subtotal,2),formatDecimal(tax,2),formatDecimal(total,2),key,auth.userId]);
 for(const line of calc){const item=await client.query<{id:string}>(`INSERT INTO sales_return_items(sales_return_id,invoice_item_id,product_id,quantity,unit_price,tax_rate,tax_amount,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[returned.rows[0].id,line.row.id,line.row.product_id,line.requested.quantity,line.row.unit_price,line.row.tax_rate,formatDecimal(line.tax,2),formatDecimal(line.total,2)]);await client.query(`UPDATE sales_invoice_items SET returned_quantity=returned_quantity+$1::numeric WHERE id=$2`,[line.requested.quantity,line.row.id]);await receiveInventory(client,{companyId:auth.companyId,warehouseId:invoice.warehouse_id,productId:line.row.product_id,quantity:line.requested.quantity,unitCost:line.row.cost_price});await client.query(`INSERT INTO stock_movements(company_id,warehouse_id,product_id,movement_type,quantity,unit_cost,source_type,source_id,source_line_id,operation_key,business_date,created_by) VALUES($1,$2,$3,'return',$4,$5,'sales_return',$6,$7,$8,$9,$10)`,[auth.companyId,invoice.warehouse_id,line.row.product_id,line.requested.quantity,line.row.cost_price,returned.rows[0].id,item.rows[0].id,key,input.businessDate,auth.userId]);}
 const cumulative=parseDecimal(invoice.returned_amount,2)+total;await client.query(`UPDATE sales_invoices SET returned_amount=$1,posting_state=CASE WHEN $1>=total THEN 'returned' ELSE 'partially_returned' END,remaining_amount=GREATEST(remaining_amount-$2::numeric,0),updated_at=now() WHERE id=$3`,[formatDecimal(cumulative,2),formatDecimal(total,2),invoiceId]);if(invoice.customer_id)await client.query(`UPDATE customers SET total_sales=total_sales-$1::numeric,balance=balance-$1::numeric,updated_at=now() WHERE id=$2 AND company_id=$3`,[formatDecimal(total,2),invoice.customer_id,auth.companyId]);
 const revenueLines=[{accountRole:'sales_revenue',debit:formatDecimal(subtotal,2),credit:'0'},{accountRole:'receivable',debit:'0',credit:formatDecimal(total,2),partyType:invoice.customer_id?'customer':undefined,partyId:invoice.customer_id??undefined}];if(tax>0n)revenueLines.splice(1,0,{accountRole:'tax_payable',debit:formatDecimal(tax,2),credit:'0'});await postJournal(client,{companyId:auth.companyId,userId:auth.userId,businessDate:input.businessDate,description:`Sales return ${number}`,sourceType:'sales_return',sourceId:returned.rows[0].id,postingType:'return',operationKey:key,lines:revenueLines});if(cost>0n)await postJournal(client,{companyId:auth.companyId,userId:auth.userId,businessDate:input.businessDate,description:`Return COGS ${number}`,sourceType:'sales_return',sourceId:returned.rows[0].id,postingType:'return_cogs',operationKey:`${key}:cogs`,lines:[{accountRole:'inventory',debit:formatDecimal(cost,2),credit:'0'},{accountRole:'cogs',debit:'0',credit:formatDecimal(cost,2)}]});
 const body={data:{id:returned.rows[0].id,returnNumber:number,total:formatDecimal(total,2)}};await appendAuditEvent(client,{tenantId:auth.tenantId,companyId:auth.companyId,actorUserId:auth.userId,action:'sales_return.posted',entityType:'sales_return',entityId:returned.rows[0].id,operationKey:key,after:body.data});await completeIdempotent(client,{companyId:auth.companyId,key,resourceType:'sales_return',resourceId:returned.rows[0].id,statusCode:201,body});return{kind:'created' as const,statusCode:201,body};
}
