import type { PoolClient } from 'pg';
import { HttpError } from '../../lib/http.js';
import { assertOpenPeriod } from '../accounting/period-service.js';
export async function actOnExpense(c:PoolClient,companyId:string,userId:string,id:string,action:'submit'|'approve'|'reject'|'pay',accountId?:string){
 const e=(await c.query<{status:string;total:string;expense_date:string|Date;description:string}>(`SELECT * FROM expenses WHERE id=$1 AND company_id=$2 FOR UPDATE`,[id,companyId])).rows[0];if(!e)throw new HttpError(404,'EXPENSE_NOT_FOUND','Expense not found');
 const allowed:Record<string,string[]>={submit:['draft'],approve:['submitted'],reject:['submitted'],pay:['approved']};if(!allowed[action].includes(e.status))throw new HttpError(409,'INVALID_EXPENSE_STATE','Invalid expense state');
 if(action==='pay'){if(!accountId)throw new HttpError(422,'ACCOUNT_REQUIRED','Payment account is required');const date=e.expense_date instanceof Date?e.expense_date.toISOString().slice(0,10):e.expense_date;await assertOpenPeriod(c,companyId,date);const a=(await c.query<{balance:string}>(`SELECT balance::text FROM financial_accounts WHERE id=$1 AND company_id=$2 FOR UPDATE`,[accountId,companyId])).rows[0];if(!a||Number(a.balance)<Number(e.total))throw new HttpError(409,'INSUFFICIENT_FUNDS','Insufficient account balance');await c.query(`UPDATE financial_accounts SET balance=balance-$1::numeric WHERE id=$2`,[e.total,accountId]);await c.query(`INSERT INTO financial_movements(company_id,account_id,movement_type,amount,business_date,description,source_type,source_id,created_by)VALUES($1,$2,'expense',$3::numeric * -1,$4,$5,'expense',$6,$7)`,[companyId,accountId,e.total,date,e.description,id,userId]);}
 const status=action==='submit'?'submitted':action==='approve'?'approved':action==='reject'?'rejected':'paid';return(await c.query(`UPDATE expenses SET status=$3,submitted_by=CASE WHEN $3='submitted' THEN $4 ELSE submitted_by END,approved_by=CASE WHEN $3 IN('approved','rejected') THEN $4 ELSE approved_by END,paid_by=CASE WHEN $3='paid' THEN $4 ELSE paid_by END,financial_account_id=COALESCE($5,financial_account_id),updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[id,companyId,status,userId,accountId??null])).rows[0];
}
