import { useMemo, useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { getBrands, getCategories, getProducts } from '@storefront/data-access';
import { useApi } from '../../hooks/useApi';
import { ProductGrid } from '../../components/storefront/ProductCard';
import { EmptyState, ErrorState, ProductGridSkeleton } from '../../components/ui/States';
import { parseCatalogQuery, updateCatalogSearch } from './catalogQuery';

export default function ProductsPage() {
  const { t } = useTranslation(); const params = useParams(); const [searchParams, setSearchParams] = useSearchParams(); const [filtersOpen, setFiltersOpen] = useState(false);
  const query = useMemo(() => parseCatalogQuery(searchParams, params), [params, searchParams]);
  const productsState = useApi((signal) => getProducts(query, signal), [JSON.stringify(query)]); const facetsState = useApi(async (signal) => { const [categories, brands] = await Promise.all([getCategories(signal), getBrands(signal)]); return { categories, brands }; });
  const setFilter = (key, value) => setSearchParams(updateCatalogSearch(searchParams, key, value));
  const active = [...searchParams.entries()].filter(([key]) => !['page', 'sort'].includes(key)); const pages = Math.max(1, Math.ceil((productsState.data?.total || 0) / 12));
  return <main className="catalog-page"><div className="container"><nav className="breadcrumb"><span>Home</span><span>/</span><strong>{t('products')}</strong></nav><div className="catalog-header"><div><span className="section-kicker">Live catalog</span><h1>{query.search ? `Search: ${query.search}` : t('products')}</h1><p>{productsState.data?.total || 0} {t('results')}</p></div><div className="catalog-actions"><button className="btn btn--ghost mobile-filter-button" onClick={() => setFiltersOpen(true)}>{t('filters')}</button><label>{t('sort')}<select value={query.sort} onChange={(event) => setFilter('sort', event.target.value)}><option value="relevance">Relevance</option><option value="newest">{t('newest')}</option><option value="price-asc">{t('priceLow')}</option><option value="price-desc">{t('priceHigh')}</option><option value="discount">{t('discount')}</option></select></label></div></div>
    {active.length ? <div className="active-filters">{active.map(([key, value]) => <button key={key} onClick={() => setFilter(key, '')}>{key}: {value} ×</button>)}<button onClick={() => setSearchParams(query.sort !== 'relevance' ? { sort: query.sort } : {})}>{t('clearFilters')}</button></div> : null}
    <div className="catalog-layout"><button className={`filter-backdrop${filtersOpen ? ' is-open' : ''}`} onClick={() => setFiltersOpen(false)} aria-label="Close filters"/><aside className={`filters-panel${filtersOpen ? ' is-open' : ''}`}><div className="filters-title"><h2>{t('filters')}</h2><button className="icon-btn" onClick={() => setFiltersOpen(false)}>×</button></div><FilterGroup title="Category" items={facetsState.data?.categories.map((item) => ({ label: item.name, value: item.slug, count: item.productCount })) || []} value={query.category} onChange={(value) => setFilter('category', value)}/><FilterGroup title="Brand" items={facetsState.data?.brands.map((item) => ({ label: item.name, value: item.name, count: item.productCount })) || []} value={query.brand} onChange={(value) => setFilter('brand', value)}/><fieldset className="filter-group"><legend>Price</legend><div className="price-inputs"><input type="number" min="0" placeholder="Min" value={query.minPrice ?? ''} onChange={(event) => setFilter('minPrice', event.target.value)}/><input type="number" min="0" placeholder="Max" value={query.maxPrice ?? ''} onChange={(event) => setFilter('maxPrice', event.target.value)}/></div></fieldset><fieldset className="filter-group"><legend>Availability</legend><label><input type="checkbox" checked={query.availability === 'in_stock'} onChange={(event) => setFilter('availability', event.target.checked ? 'in_stock' : '')}/> In stock</label></fieldset></aside>
      <section className="catalog-results">{productsState.loading ? <ProductGridSkeleton count={8}/> : productsState.error ? <ErrorState message={t('apiError')} onRetry={productsState.retry}/> : productsState.data?.products.length ? <ProductGrid products={productsState.data.products}/> : <EmptyState title={t('noProducts')} action={<button className="btn btn--primary" onClick={() => setSearchParams({})}>{t('clearFilters')}</button>}/>} {pages > 1 ? <nav className="pagination" aria-label="Pagination">{Array.from({ length: pages }, (_, index) => index + 1).map((page) => <button className={page === query.page ? 'is-active' : ''} onClick={() => setFilter('page', String(page))} key={page}>{page}</button>)}</nav> : null}</section>
    </div></div></main>;
}

function FilterGroup({ title, items, value, onChange }) { return <fieldset className="filter-group"><legend>{title}</legend>{items.map((item) => <label key={item.value}><input type="radio" name={title} checked={value === item.value} onChange={() => onChange(item.value)}/><span>{item.label}</span><small>{item.count}</small></label>)}</fieldset>; }
