import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { getProduct, getRelatedProducts } from '@storefront/data-access';
import { useApi } from '../../hooks/useApi';
import { useStore } from '../../app/StoreProvider';
import { formatMoney, localized, ProductGrid } from '../../components/storefront/ProductCard';
import { ErrorState, PageLoader } from '../../components/ui/States';

export default function ProductPage() {
  const { slug } = useParams(); const navigate = useNavigate(); const { t, i18n } = useTranslation(); const { addToCart, toggleWishlist, wishlist } = useStore();
  const { data: product, loading, error, retry } = useApi((signal) => getProduct(slug, signal), [slug]); const related = useApi((signal) => getRelatedProducts(slug, signal), [slug]);
  const [selectedImage, setSelectedImage] = useState(0); const [variantId, setVariantId] = useState(''); const [quantity, setQuantity] = useState(1);
  useEffect(() => { if (!product) return; const viewed = JSON.parse(localStorage.getItem('malek_recently_viewed') || '[]'); localStorage.setItem('malek_recently_viewed', JSON.stringify([product.slug, ...viewed.filter((item) => item !== product.slug)].slice(0, 8))); document.title = product.seoTitle || `${product.name} | Malek Stores`; }, [product]);
  const variant = product?.variants?.find((item) => item.id === variantId); const displayPrice = variant?.price ?? product?.price; const displayOriginal = variant?.originalPrice ?? product?.originalPrice; const media = useMemo(() => product?.media?.filter((item) => item.mediaType === 'image') || (product?.primaryImage ? [product.primaryImage] : []), [product]);
  if (loading) return <PageLoader/>; if (error) return <main className="section container"><ErrorState message={error.status === 404 ? 'Product not found' : t('apiError')} onRetry={retry}/></main>; if (!product) return null;
  const wished = wishlist.some((item) => item.slug === product.slug); const canAdd = product.availability !== 'out_of_stock' && (!product.hasVariants || variantId);
  const add = async (buyNow = false) => { if (!canAdd) return; await addToCart(product, variantId || undefined, quantity); if (buyNow) navigate('/checkout'); };
  return <main className="product-page"><div className="container"><nav className="breadcrumb"><Link to="/">Home</Link><span>/</span><Link to={`/category/${product.categorySlug}`}>{product.categoryName}</Link><span>/</span><strong>{product.name}</strong></nav><div className="product-detail-grid">
    <section className="product-gallery" aria-label="Product images"><div className="product-gallery__main">{media[selectedImage] ? <img src={media[selectedImage].url} alt={media[selectedImage].altText || product.name} width={media[selectedImage].width || 900} height={media[selectedImage].height || 900}/> : <div className="product-gallery__empty">M</div>}</div>{media.length > 1 ? <div className="product-thumbnails">{media.map((item, index) => <button className={selectedImage === index ? 'is-active' : ''} onClick={() => setSelectedImage(index)} key={item.id}><img src={item.thumbnailUrl || item.url} alt=""/></button>)}</div> : null}</section>
    <section className="product-info"><span className="section-kicker">{product.brand}</span><h1>{localized(product.name, product.nameAr, i18n.language)}</h1><div className="product-meta"><span>SKU: {variant?.sku || product.sku}</span><span>★ {product.rating || '—'} ({product.reviewCount})</span></div><div className="product-detail-price"><strong>{formatMoney(displayPrice, product.currency, i18n.language)}</strong>{displayOriginal ? <del>{formatMoney(displayOriginal, product.currency, i18n.language)}</del> : null}</div><p className={`availability availability--${variant?.availability || product.availability}`}>{t((variant?.availability || product.availability) === 'in_stock' ? 'inStock' : (variant?.availability || product.availability) === 'low_stock' ? 'lowStock' : 'outOfStock')}</p>
      <p className="product-description">{localized(product.description, product.descriptionAr, i18n.language)}</p>{product.variants?.length ? <fieldset className="variant-selector"><legend>Choose an option</legend>{product.variants.map((item) => <button className={variantId === item.id ? 'is-active' : ''} onClick={() => setVariantId(item.id)} disabled={item.availability === 'out_of_stock'} key={item.id}><strong>{item.name}</strong>{Object.values(item.attributes).length ? <small>{Object.entries(item.attributes).map(([key, value]) => `${key}: ${value}`).join(' · ')}</small> : null}</button>)}</fieldset> : null}
      <div className="purchase-row"><label className="quantity-control"><span className="visually-hidden">Quantity</span><button onClick={() => setQuantity((value) => Math.max(1, value - 1))}>−</button><input value={quantity} readOnly/><button onClick={() => setQuantity((value) => Math.min(variant?.stockQuantity || product.stockQuantity || 1, value + 1))}>+</button></label><button className="btn btn--primary" disabled={!canAdd} onClick={() => add(false)}>{product.hasVariants && !variantId ? 'Choose an option' : t('addCart')}</button><button className="btn btn--ghost" disabled={!canAdd} onClick={() => add(true)}>{t('buyNow')}</button><button className="icon-btn wishlist-detail" onClick={() => toggleWishlist(product)} aria-pressed={wished}>{wished ? '♥' : '♡'}</button></div>
      <div className="commerce-benefits"><div><strong>Warranty</strong><span>See product warranty terms</span></div><div><strong>Delivery</strong><span>Calculated at checkout</span></div><div><strong>Secure checkout</strong><span>Server-validated availability</span></div></div>
    </section>
  </div><section className="product-specifications"><h2>Specifications</h2><dl><div><dt>Brand</dt><dd>{product.brand || '—'}</dd></div><div><dt>Model</dt><dd>{product.name}</dd></div><div><dt>Category</dt><dd>{product.categoryName || '—'}</dd></div>{variant ? Object.entries(variant.attributes).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>) : null}</dl></section>{related.data?.length ? <section className="section"><div className="section-head"><div><span className="section-kicker">Keep exploring</span><h2 className="section-title">Related products</h2></div></div><ProductGrid products={related.data}/></section> : null}</div></main>;
}
