import { type FormEvent, useEffect, useState } from 'react';
import Link from '@/components/router/Link';
import { BookOpen, Plus, Save } from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { useTranslation } from 'react-i18next';
import { apiGet, apiRequest } from '@/lib/api-client';

type Account={id:string;code:string;name:string;name_ar:string;account_type:string};
type Journal={id:string;entry_number:string;business_date:string;description:string;status:string;total_debit:string};
export function AccountingRoutePage({ slug }: { slug: string[] }) {
  const { i18n }=useTranslation(); const ar=i18n.language.startsWith('ar'); const path=slug.join('/');
  const [accounts,setAccounts]=useState<Account[]>([]); const [journals,setJournals]=useState<Journal[]>([]); const [message,setMessage]=useState('');
  useEffect(()=>{ Promise.all([apiGet<Account[]>('/accounting/accounts'),apiGet<Journal[]>('/accounting/journals')]).then(([a,j])=>{setAccounts(a);setJournals(j);}).catch((e:Error)=>setMessage(e.message)); },[]);
  if(path==='journals/new'){
    const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage('');const f=new FormData(e.currentTarget);try{await apiRequest('/accounting/journals',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({businessDate:f.get('date'),description:f.get('description'),lines:[{accountId:f.get('debitAccount'),debit:Number(f.get('amount')).toFixed(2),credit:'0.00'},{accountId:f.get('creditAccount'),debit:'0.00',credit:Number(f.get('amount')).toFixed(2)}]})});setMessage(ar?'تم حفظ المسودة بنجاح':'Draft saved successfully');e.currentTarget.reset();}catch(c){setMessage(c instanceof Error?c.message:'Failed');}};
    return <AppLayout><div className="mx-auto max-w-4xl"><h1 className="mb-6 text-2xl font-bold">{ar?'قيد يومية جديد':'New journal entry'}</h1>{message&&<div className="mb-4 rounded-xl bg-primary-50 p-4 text-primary-700">{message}</div>}<form onSubmit={submit} className="card p-5"><div className="grid gap-5 md:grid-cols-2"><div><label className="label">{ar?'التاريخ':'Date'}</label><input name="date" required type="date" className="input" defaultValue={new Date().toISOString().slice(0,10)}/></div><div><label className="label">{ar?'المبلغ':'Amount'}</label><input name="amount" required type="number" min="0.01" step="0.01" className="input"/></div><div><label className="label">{ar?'الحساب المدين':'Debit account'}</label><select name="debitAccount" required className="input">{accounts.map(a=><option key={a.id} value={a.id}>{a.code} - {ar?a.name_ar:a.name}</option>)}</select></div><div><label className="label">{ar?'الحساب الدائن':'Credit account'}</label><select name="creditAccount" required className="input">{accounts.map(a=><option key={a.id} value={a.id}>{a.code} - {ar?a.name_ar:a.name}</option>)}</select></div><div className="md:col-span-2"><label className="label">{ar?'البيان':'Description'}</label><input name="description" required minLength={3} className="input"/></div></div><div className="mt-5 flex justify-end gap-3"><Link href="/accounting/journals" className="btn btn-secondary btn-md">{ar?'إلغاء':'Cancel'}</Link><button className="btn btn-primary btn-md"><Save className="h-4 w-4"/>{ar?'حفظ':'Save'}</button></div></form></div></AppLayout>;
  }
  const isAccounts=slug[0]==='accounts'; return <AppLayout><section className="mb-6 flex items-center justify-between"><div><div className="mb-2 flex items-center gap-2 text-primary-600"><BookOpen className="h-5 w-5"/>{ar?'المحاسبة العامة':'Accounting'}</div><h1 className="text-2xl font-bold">{isAccounts?(ar?'دليل الحسابات':'Chart of accounts'):(ar?'دفتر اليومية':'Journals')}</h1></div>{!isAccounts&&<Link href="/accounting/journals/new" className="btn btn-primary btn-sm"><Plus className="h-4 w-4"/>{ar?'قيد جديد':'New entry'}</Link>}</section>{message&&<div className="mb-4 rounded-xl bg-danger-50 p-4 text-danger-700">{message}</div>}<section className="card overflow-hidden">{(isAccounts?accounts:journals).map((row)=><div key={row.id} className="flex justify-between border-b p-4 last:border-0"><div className="font-semibold">{'code'in row?`${row.code} - ${ar?row.name_ar:row.name}`:`${row.entry_number} - ${row.description}`}</div><div className="text-sm text-slate-500">{'account_type'in row?row.account_type:`${row.business_date} · ${row.status} · ${row.total_debit} EGP`}</div></div>)}</section></AppLayout>;
}
