import { useState } from 'react';
import { Link, NavLink, useLocation, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { createCustomerAddress, deleteCustomerAddress, getCustomerAddresses, getCustomerOrder, getCustomerOrders } from '../../data-access/customerApi';
import { useCustomer } from '../../app/CustomerProvider';
import { useApi } from '../../hooks/useApi';
import { formatMoney } from '../../components/storefront/ProductCard';
import { EmptyState, ErrorState, PageLoader } from '../../components/ui/States';

export default function AccountPage() {
  const { t } = useTranslation(); const { customer, loading, login, register, logout } = useCustomer(); const location = useLocation();
  if (loading) return <PageLoader/>; if (!customer) return <AuthForms login={login} register={register}/>;
  const path = location.pathname;
  return <main className="account-page"><div className="container"><nav className="breadcrumb"><Link to="/">Home</Link><span>/</span><strong>{t('account')}</strong></nav><div className="account-layout"><aside className="account-nav"><div className="account-identity"><span>{customer.name.slice(0, 1).toUpperCase()}</span><div><strong>{customer.name}</strong><small>{customer.email}</small></div></div>{[['Overview', '/account'], ['Profile', '/account/profile'], ['Addresses', '/account/addresses'], ['Orders', '/account/orders'], ['Wishlist', '/account/wishlist']].map(([label, url]) => <NavLink end={url === '/account'} to={url} key={url}>{label}</NavLink>)}<button onClick={logout}>{t('logout')}</button></aside><section className="account-content">{path === '/account' ? <Overview customer={customer}/> : path === '/account/profile' ? <Profile customer={customer}/> : path === '/account/addresses' ? <Addresses/> : path === '/account/orders' ? <Orders/> : path.startsWith('/account/orders/') ? <OrderDetails/> : <ErrorState message="Account page not found"/>}</section></div></div></main>;
}

function AuthForms({ login, register }) {
  const { t } = useTranslation(); const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  return <main className="auth-page"><form className="auth-card" onSubmit={async (event) => { event.preventDefault(); const form = new window.FormData(event.currentTarget); setSubmitting(true); setError(''); const input = { email: form.get('email'), password: form.get('password'), ...(mode === 'register' ? { name: form.get('name'), phone: form.get('phone') || undefined } : {}) }; try { await (mode === 'login' ? login(input) : register(input)); } catch (err) { setError(err.message); } finally { setSubmitting(false); } }}><Link className="logo" to="/"><span className="logo__mark"/><span>Malek Stores</span></Link><span className="section-kicker">Customer account</span><h1>{mode === 'login' ? t('login') : 'Create account'}</h1>{error ? <div className="inline-error" role="alert">{error}</div> : null}{mode === 'register' ? <><label>Full name<input name="name" autoComplete="name" required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel"/></label></> : null}<label>{t('email')}<input name="email" type="email" autoComplete="email" spellCheck="false" required/></label><label>{t('password')}<input name="password" type="password" minLength="8" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} required/></label><button className="btn btn--primary btn--block" disabled={submitting}>{submitting ? 'Working…' : mode === 'login' ? t('login') : 'Create account'}</button><button className="text-link" type="button" onClick={() => { setMode((value) => value === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create a customer account' : 'Already have an account? Log in'}</button></form></main>;
}
function Overview({ customer }) { return <><span className="section-kicker">Welcome back</span><h1>{customer.name}</h1><div className="account-cards"><article><strong>Profile</strong><p>{customer.email}</p><Link to="/account/profile">View profile</Link></article><article><strong>Orders</strong><p>Track purchases and fulfillment.</p><Link to="/account/orders">View orders</Link></article></div></>; }
function Profile({ customer }) { return <><h1>Profile</h1><dl className="profile-list"><div><dt>Name</dt><dd>{customer.name}</dd></div><div><dt>Email</dt><dd>{customer.email}</dd></div><div><dt>Phone</dt><dd>{customer.phone || '—'}</dd></div></dl></>; }
function Addresses() {
  const state=useApi(()=>getCustomerAddresses()); const [adding,setAdding]=useState(false);
  if(state.loading)return <PageLoader/>; if(state.error)return <ErrorState message={state.error.message} onRetry={state.retry}/>;
  return <><div className="section-head"><h1>Addresses</h1><button className="btn btn--primary" onClick={()=>setAdding((value)=>!value)}>Add address</button></div>{adding?<form className="address-form" onSubmit={async(event)=>{event.preventDefault();const form=new window.FormData(event.currentTarget);await createCustomerAddress(Object.fromEntries(form));setAdding(false);state.retry();}}><label>Label<input name="label" defaultValue="Home" required/></label><label>Recipient<input name="recipientName" autoComplete="name" required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required/></label><label className="form-span">Address<input name="addressLine1" autoComplete="street-address" required/></label><label>City<input name="city" autoComplete="address-level2" required/></label><label>Area<input name="area" autoComplete="address-level3"/></label><button className="btn btn--primary">Save address</button></form>:null}{state.data.length?<div className="address-grid">{state.data.map((address)=><article key={address.id}><strong>{address.label}</strong><p>{address.recipientName}<br/>{address.addressLine1}<br/>{address.area}, {address.city}<br/>{address.phone}</p><button className="text-link" onClick={async()=>{await deleteCustomerAddress(address.id);state.retry();}}>Remove</button></article>)}</div>:<EmptyState title="No saved addresses"/>}</>;
}
function Orders(){const state=useApi(()=>getCustomerOrders());if(state.loading)return <PageLoader/>;if(state.error)return <ErrorState message={state.error.message} onRetry={state.retry}/>;return <><h1>Orders</h1>{state.data.length?<div className="orders-list">{state.data.map(order=><Link to={`/account/orders/${order.id}`} className="order-card" key={order.id}><div><strong>{order.orderNumber}</strong><small>{new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(order.createdAt))}</small></div><span className={`status-badge status-badge--${order.status}`}>{order.status}</span><b>{formatMoney(order.total,order.currency,'en')}</b></Link>)}</div>:<EmptyState title="No orders yet" action={<Link className="btn btn--primary" to="/products">Shop products</Link>}/>}</>}
function OrderDetails(){const { '*':rest }=useParams();const id=rest?.split('/').pop();const state=useApi(()=>getCustomerOrder(id),[id]);if(state.loading)return <PageLoader/>;if(state.error)return <ErrorState message={state.error.message} onRetry={state.retry}/>;const order=state.data;return <><Link className="text-link" to="/account/orders">← All orders</Link><h1>{order.orderNumber}</h1><div className="order-detail-meta"><span className={`status-badge status-badge--${order.status}`}>{order.status}</span><span>Payment: {order.paymentStatus}</span></div><div className="order-items">{order.items.map(item=><article key={item.id}><div><strong>{item.productName}</strong><small>{item.sku} · Qty {item.quantity}</small></div><b>{formatMoney(item.total,order.currency,'en')}</b></article>)}</div><div className="order-summary"><div className="summary-row"><span>Subtotal</span><b>{formatMoney(order.subtotal,order.currency,'en')}</b></div><div className="summary-row"><span>Shipping</span><b>{formatMoney(order.shippingAmount,order.currency,'en')}</b></div><div className="summary-row summary-row--total"><span>Total</span><b>{formatMoney(order.total,order.currency,'en')}</b></div></div></>}
