import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = { home:'Home',products:'Products',categories:'Categories',search:'Search',wishlist:'Wishlist',account:'Account',cart:'Cart',compare:'Compare',shopNow:'Shop now',latest:'Latest arrivals',best:'Best sellers',recommended:'Recommended for you',recentlyViewed:'Recently viewed',addCart:'Add to cart',buyNow:'Buy now',inStock:'In stock',lowStock:'Low stock',outOfStock:'Out of stock',retry:'Try again',loading:'Loading',noProducts:'No products match these filters.',clearFilters:'Clear filters',filters:'Filters',subtotal:'Subtotal',tax:'Tax',shipping:'Shipping',total:'Total',checkout:'Checkout',emptyCart:'Your cart is empty.',emptyWishlist:'Your wishlist is empty.',moveToCart:'Move to cart',login:'Log in',logout:'Log out',email:'Email',password:'Password',checkoutTitle:'Secure checkout',deliveryMethod:'Delivery method',paymentMethod:'Payment method',reviewOrder:'Review order',searchPlaceholder:'Search phones, brands and categories',results:'results',sort:'Sort',newest:'Newest',priceLow:'Price: low to high',priceHigh:'Price: high to low',discount:'Biggest discount',apiError:'We could not load this content.',unavailable:'This feature needs additional backend support.',notFound:'Page not found',backHome:'Back to home' };
const ar = { home:'الرئيسية',products:'المنتجات',categories:'الأقسام',search:'بحث',wishlist:'المفضلة',account:'حسابي',cart:'السلة',compare:'مقارنة',shopNow:'تسوق الآن',latest:'أحدث المنتجات',best:'الأكثر مبيعاً',recommended:'مقترحة لك',recentlyViewed:'شاهدت مؤخراً',addCart:'أضف للسلة',buyNow:'اشتر الآن',inStock:'متوفر',lowStock:'كمية محدودة',outOfStock:'غير متوفر',retry:'حاول مرة أخرى',loading:'جاري التحميل',noProducts:'لا توجد منتجات مطابقة للفلاتر.',clearFilters:'مسح الفلاتر',filters:'الفلاتر',subtotal:'المجموع الفرعي',tax:'الضريبة',shipping:'التوصيل',total:'الإجمالي',checkout:'إتمام الشراء',emptyCart:'السلة فارغة.',emptyWishlist:'قائمة المفضلة فارغة.',moveToCart:'انقل للسلة',login:'تسجيل الدخول',logout:'تسجيل الخروج',email:'البريد الإلكتروني',password:'كلمة المرور',checkoutTitle:'دفع آمن',deliveryMethod:'طريقة التوصيل',paymentMethod:'طريقة الدفع',reviewOrder:'مراجعة الطلب',searchPlaceholder:'ابحث عن موبايل أو علامة تجارية أو قسم',results:'نتيجة',sort:'الترتيب',newest:'الأحدث',priceLow:'السعر: الأقل أولاً',priceHigh:'السعر: الأعلى أولاً',discount:'أكبر خصم',apiError:'تعذر تحميل المحتوى.',unavailable:'هذه الميزة تحتاج إلى دعم إضافي من الخادم.',notFound:'الصفحة غير موجودة',backHome:'العودة للرئيسية' };

const initialLanguage = localStorage.getItem('malek_lang') || 'ar';
i18n.use(initReactI18next).init({ resources: { en:{translation:en}, ar:{translation:ar} }, lng: initialLanguage, fallbackLng: 'en', interpolation: { escapeValue: false } });
i18n.on('languageChanged', (language) => { localStorage.setItem('malek_lang', language); document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; });
document.documentElement.lang = initialLanguage;
document.documentElement.dir = initialLanguage === 'ar' ? 'rtl' : 'ltr';
export default i18n;
