import { X, Play, BookOpen, Trash2 } from 'lucide-react';
import { catalogByType, getNodeGuide, RETAIL_EVENTS } from '../domain/catalog';

export default function NodeConfigPanel({node,onChange,onClose,onDelete}){
  if(!node)return <aside data-tour="node-config" className="hidden h-full w-[300px] shrink-0 border-l border-[var(--border)] bg-[var(--card)] p-6 xl:block"><p className="text-sm font-semibold">Node configuration</p><p className="mt-2 text-xs leading-relaxed text-[var(--muted-foreground)]">Select a node to configure inputs, retry policy, timeouts, connections, and error behavior.</p></aside>;
  const definition=catalogByType[node.data.nodeType]; const guide=getNodeGuide(definition); const update=(key,value)=>onChange({...node,data:{...node.data,config:{...node.data.config,[key]:value}}});
  return <aside data-tour="node-config" className="h-full w-[300px] shrink-0 overflow-y-auto border-l border-[var(--border)] bg-[var(--card)]">
    <div data-tour="node-config-summary" className="sticky top-0 z-10 flex items-center justify-between border-b border-[var(--border)] bg-[var(--card)] p-3"><div><p className="text-xs font-semibold">{node.data.label}</p><p className="text-[10px] text-[var(--muted-foreground)]">{definition?.description}</p></div><button onClick={onClose} aria-label="Close configuration"><X size={16}/></button></div>
    <div data-tour="node-config-fields" className="space-y-4 p-4"><Field label="Node label"><input value={node.data.label} onChange={e=>onChange({...node,data:{...node.data,label:e.target.value}})} className="workflow-input"/></Field>
      {node.data.nodeType==='retailEventTrigger'&&<Field label="Retail event"><select value={node.data.config.eventType||''} onChange={e=>update('eventType',e.target.value)} className="workflow-input">{RETAIL_EVENTS.map(e=><option key={e}>{e}</option>)}</select></Field>}
      {node.data.category==='agent'&&<><div className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-2.5"><p className="text-[10px] font-semibold text-blue-500">LLM-powered node</p><p className="mt-1 text-[9px] leading-4 text-[var(--muted-foreground)]">This node sends scoped upstream workflow data to the configured local Ollama model when executed.</p></div><Field label="Agent role"><input value={node.data.config.role||''} onChange={e=>update('role',e.target.value)} className="workflow-input"/></Field><Field label="System instruction"><textarea value={node.data.config.systemInstruction||''} onChange={e=>update('systemInstruction',e.target.value)} rows={4} placeholder="Keep recommendations scoped to the current store..." className="workflow-input"/></Field><div className="grid grid-cols-2 gap-2"><Field label="Max steps"><input type="number" value={node.data.config.maxSteps||6} onChange={e=>update('maxSteps',+e.target.value)} className="workflow-input"/></Field><Field label="Temperature"><input type="number" step=".1" min="0" max="2" value={node.data.config.temperature??.2} onChange={e=>update('temperature',+e.target.value)} className="workflow-input"/></Field></div><Field label="Ollama model"><input value={node.data.config.model||'qwen2.5-coder:7b'} onChange={e=>update('model',e.target.value)} className="workflow-input"/></Field></>}
      <div className="grid grid-cols-2 gap-2"><Field label="Timeout (ms)"><input type="number" value={node.data.config.timeoutMs||30000} onChange={e=>update('timeoutMs',+e.target.value)} className="workflow-input"/></Field><Field label="Retries"><input type="number" value={node.data.config.retry?.maxAttempts||1} onChange={e=>update('retry',{...node.data.config.retry,maxAttempts:+e.target.value})} className="workflow-input"/></Field></div>
      <Field label="On error"><select value={node.data.config.errorBehavior||'stop'} onChange={e=>update('errorBehavior',e.target.value)} className="workflow-input"><option value="stop">Stop workflow</option><option value="continue">Continue</option><option value="errorBranch">Use error branch</option></select></Field>
      <div className="rounded-lg border border-[var(--border)] bg-[var(--muted)] p-3"><p className="flex items-center gap-2 text-[11px] font-semibold"><BookOpen size={13}/>How to use this node</p><p className="mt-1 text-[10px] leading-relaxed text-[var(--muted-foreground)]">{guide.howToUse}</p><p className="mt-2 text-[10px] leading-relaxed text-[var(--muted-foreground)]"><span className="font-semibold text-[var(--foreground)]">Input:</span> {guide.input}</p><p className="mt-1 text-[10px] leading-relaxed text-[var(--muted-foreground)]"><span className="font-semibold text-[var(--foreground)]">Output:</span> {guide.output}</p><p className="mt-2 text-[10px] leading-relaxed text-[var(--muted-foreground)]">Upstream values use safe expressions such as {'{{ nodes.nodeId.output.field }}'}.</p></div>
      <button className="ui-button w-full px-3 py-2 text-xs"><Play size={13}/>Test node</button><button onClick={()=>onDelete(node.id)} className="flex w-full items-center justify-center gap-2 rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-500 hover:bg-red-500/10"><Trash2 size={13}/>Delete node</button>
    </div>
  </aside>
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wide text-[var(--muted-foreground)]">{label}</span>{children}</label>}
