import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useStore } from '../../app/StoreProvider';
import { formatMoney, localized } from '../../components/storefront/ProductCard';
import { EmptyState, ErrorState } from '../../components/ui/States';

export default function CartPage() {
  const { t, i18n } = useTranslation(); const { cart, cartLoading, cartError, refreshCart, updateQuantity, removeFromCart } = useStore();
  if (cartError && !cart) return <main className="section container"><ErrorState message={t('apiError')} onRetry={refreshCart}/></main>;
  if (!cart?.lines.length) return <main className="section container"><EmptyState title={t('emptyCart')} action={<Link className="btn btn--primary" to="/products">{t('shopNow')}</Link>}/></main>;
  return <main className="cart-page"><div className="container"><nav className="breadcrumb"><Link to="/">Home</Link><span>/</span><strong>{t('cart')}</strong></nav><h1>{t('cart')}</h1><div className="cart-layout"><section className="cart-list" aria-busy={cartLoading}>{cart.lines.map((line) => <article className="cart-page-item" key={line.id}>{line.imageUrl ? <img src={line.imageUrl} alt=""/> : <div className="cart-item__thumb"/>}<div><Link to={`/product/${line.slug}`}><h2>{localized(line.name, line.nameAr, i18n.language)}</h2></Link><p>{line.sku}</p><strong>{formatMoney(line.unitPrice, cart.currency, i18n.language)}</strong></div><label className="quantity-control"><button onClick={() => line.quantity > 1 && updateQuantity(line.id, line.quantity - 1)} disabled={cartLoading}>−</button><input value={line.quantity} readOnly aria-label="Quantity"/><button onClick={() => updateQuantity(line.id, line.quantity + 1)} disabled={cartLoading || line.quantity >= line.maxQuantity}>+</button></label><strong>{formatMoney(line.lineSubtotal + line.taxAmount, cart.currency, i18n.language)}</strong><button className="icon-btn" onClick={() => removeFromCart(line.id)} disabled={cartLoading} aria-label="Remove">×</button></article>)}</section><aside className="order-summary"><h2>Order summary</h2><div className="summary-row"><span>{t('subtotal')}</span><strong>{formatMoney(cart.subtotal, cart.currency, i18n.language)}</strong></div><div className="summary-row"><span>{t('tax')}</span><strong>{formatMoney(cart.taxTotal, cart.currency, i18n.language)}</strong></div><div className="summary-row summary-row--total"><span>{t('total')}</span><strong>{formatMoney(cart.total, cart.currency, i18n.language)}</strong></div><Link className="btn btn--primary btn--block" to="/checkout">{t('checkout')}</Link></aside></div></div></main>;
}
