import { Router } from "express";
import { z } from "zod";
import { query } from "../../db/client.js";
import { HttpError, validate } from "../../lib/http.js";
import { serializeRows } from "../../lib/rows.js";
import { authorizeAny } from "../auth/middleware.js";

type ReportDefinition = { title: string; sql: string; dateField?: string; note?: string };
const invoiceFilter = "i.company_id=$1 AND ($2::date IS NULL OR i.invoice_date >= $2) AND ($3::date IS NULL OR i.invoice_date <= $3)";
const movementFilter = "m.company_id=$1 AND ($2::date IS NULL OR m.business_date >= $2) AND ($3::date IS NULL OR m.business_date <= $3)";
const journalFilter = "e.company_id=$1 AND e.status='posted' AND ($2::date IS NULL OR e.business_date >= $2) AND ($3::date IS NULL OR e.business_date <= $3)";
const purchaseFilter = "o.company_id=$1 AND ($2::date IS NULL OR o.order_date >= $2) AND ($3::date IS NULL OR o.order_date <= $3)";

const reports: Record<string, ReportDefinition> = {
  "sales/daily": { title: "Daily sales", sql: `SELECT i.invoice_date date,count(*)::int invoices,COALESCE(sum(i.subtotal),0) subtotal,COALESCE(sum(i.tax_amount),0) tax,COALESCE(sum(i.total),0) total,COALESCE(sum(i.paid_amount),0) paid FROM sales_invoices i WHERE ${invoiceFilter} GROUP BY i.invoice_date ORDER BY i.invoice_date DESC` },
  "sales/monthly": { title: "Monthly sales", sql: `SELECT to_char(date_trunc('month',i.invoice_date::timestamp),'YYYY-MM') AS report_month,count(*)::int invoices,COALESCE(sum(i.total),0) total,COALESCE(sum(i.paid_amount),0) paid,COALESCE(sum(i.remaining_amount),0) outstanding FROM sales_invoices i WHERE ${invoiceFilter} GROUP BY date_trunc('month',i.invoice_date::timestamp) ORDER BY date_trunc('month',i.invoice_date::timestamp) DESC` },
  "sales/by-product": { title: "Sales by product", sql: `SELECT p.sku,p.name,p.name_ar,COALESCE(sum(x.quantity-x.returned_quantity),0) quantity,COALESCE(sum(x.total),0) revenue,COALESCE(sum((x.quantity-x.returned_quantity)*x.cost_price),0) cost,COALESCE(sum(x.total-(x.quantity-x.returned_quantity)*x.cost_price),0) gross_profit FROM sales_invoice_items x JOIN sales_invoices i ON i.id=x.invoice_id LEFT JOIN products p ON p.id=x.product_id WHERE ${invoiceFilter} GROUP BY p.id,p.sku,p.name,p.name_ar ORDER BY revenue DESC` },
  "sales/by-customer": { title: "Sales by customer", sql: `SELECT COALESCE(c.code,'WALK-IN') code,COALESCE(c.name,i.customer_name,'Walk-in') customer,count(*)::int invoices,COALESCE(sum(i.total),0) sales,COALESCE(sum(i.paid_amount),0) paid,COALESCE(sum(i.remaining_amount),0) outstanding FROM sales_invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE ${invoiceFilter} GROUP BY c.id,c.code,c.name,i.customer_name ORDER BY sales DESC` },
  "sales/by-branch": { title: "Sales by branch", sql: `SELECT COALESCE(w.code,'UNASSIGNED') code,COALESCE(w.name,'Unassigned warehouse') branch,count(*)::int invoices,COALESCE(sum(i.total),0) sales FROM sales_invoices i LEFT JOIN warehouses w ON w.id=i.warehouse_id WHERE ${invoiceFilter} GROUP BY w.id,w.code,w.name ORDER BY sales DESC`, note: "Sales currently carry warehouse rather than branch ownership; warehouse is used as the operational location." },
  "sales/profitability": { title: "Profitability analysis", sql: `SELECT i.invoice_number,i.invoice_date,COALESCE(c.name,i.customer_name,'Walk-in') customer,i.total revenue,COALESCE(sum((x.quantity-x.returned_quantity)*x.cost_price),0) cost,i.total-COALESCE(sum((x.quantity-x.returned_quantity)*x.cost_price),0) gross_profit FROM sales_invoices i LEFT JOIN customers c ON c.id=i.customer_id JOIN sales_invoice_items x ON x.invoice_id=i.id WHERE ${invoiceFilter} GROUP BY i.id,c.name ORDER BY i.invoice_date DESC` },

  "inventory/balance": { title: "Stock balance", sql: `SELECT w.code warehouse,p.sku,p.name,p.name_ar,b.on_hand,b.reserved,b.available,b.average_cost,b.on_hand*b.average_cost value FROM inventory_balances b JOIN warehouses w ON w.id=b.warehouse_id JOIN products p ON p.id=b.product_id WHERE b.company_id=$1 ORDER BY p.name,w.code` },
  "inventory/valuation": { title: "Inventory valuation", sql: `SELECT p.sku,p.name,p.name_ar,COALESCE(sum(b.on_hand),0) quantity,CASE WHEN sum(b.on_hand)=0 THEN 0 ELSE sum(b.on_hand*b.average_cost)/sum(b.on_hand) END average_cost,COALESCE(sum(b.on_hand*b.average_cost),0) value FROM products p LEFT JOIN inventory_balances b ON b.product_id=p.id AND b.company_id=p.company_id WHERE p.company_id=$1 GROUP BY p.id ORDER BY value DESC` },
  "inventory/movements": { title: "Stock movements", sql: `SELECT m.business_date,w.code warehouse,p.sku,p.name,m.movement_type,m.quantity,m.unit_cost,m.quantity*m.unit_cost value,m.source_type,m.reason FROM stock_movements m JOIN warehouses w ON w.id=m.warehouse_id JOIN products p ON p.id=m.product_id WHERE ${movementFilter} ORDER BY m.business_date DESC,m.created_at DESC` },
  "inventory/low-stock": { title: "Low stock", sql: `SELECT p.sku,p.name,p.name_ar,p.reorder_level,COALESCE(sum(b.available),0) available,p.reorder_level-COALESCE(sum(b.available),0) shortage FROM products p LEFT JOIN inventory_balances b ON b.product_id=p.id WHERE p.company_id=$1 AND p.is_active=true GROUP BY p.id HAVING COALESCE(sum(b.available),0)<=p.reorder_level ORDER BY shortage DESC` },
  "inventory/slow-moving": { title: "Slow-moving products", sql: `SELECT p.sku,p.name,p.name_ar,COALESCE(sum(b.on_hand),0) on_hand,max(m.business_date) last_movement,(current_date-max(m.business_date))::int days_since_movement FROM products p LEFT JOIN inventory_balances b ON b.product_id=p.id LEFT JOIN stock_movements m ON m.product_id=p.id AND m.company_id=p.company_id WHERE p.company_id=$1 GROUP BY p.id HAVING max(m.business_date) IS NULL OR max(m.business_date)<current_date-interval '60 days' ORDER BY last_movement NULLS FIRST` },
  "inventory/expiry": { title: "Expiry report", sql: `SELECT p.sku,p.name,p.name_ar,COALESCE(sum(b.on_hand),0) on_hand,'not_tracked' tracking_status FROM products p LEFT JOIN inventory_balances b ON b.product_id=p.id WHERE p.company_id=$1 GROUP BY p.id ORDER BY p.name`, note: "Lot and expiry dates are not yet stored; this report identifies stocked products whose expiry is not tracked." },

  "accounting/trial-balance": { title: "Trial balance", sql: `SELECT a.code,a.name,a.name_ar,a.account_type,COALESCE(sum(l.debit),0) debit,COALESCE(sum(l.credit),0) credit,COALESCE(sum(l.debit-l.credit),0) balance FROM ledger_accounts a LEFT JOIN journal_lines l ON l.ledger_account_id=a.id LEFT JOIN journal_entries e ON e.id=l.journal_entry_id AND ${journalFilter} WHERE a.company_id=$1 GROUP BY a.id ORDER BY a.code` },
  "accounting/income-statement": { title: "Income statement", sql: `SELECT a.code,a.name,a.account_type,CASE WHEN a.account_type='revenue' THEN COALESCE(sum(l.credit-l.debit),0) ELSE COALESCE(sum(l.debit-l.credit),0) END amount FROM ledger_accounts a JOIN journal_lines l ON l.ledger_account_id=a.id JOIN journal_entries e ON e.id=l.journal_entry_id WHERE ${journalFilter} AND a.account_type IN('revenue','expense') GROUP BY a.id ORDER BY a.account_type DESC,a.code` },
  "accounting/balance-sheet": { title: "Balance sheet", sql: `SELECT a.code,a.name,a.account_type,CASE WHEN a.account_type='asset' THEN COALESCE(sum(l.debit-l.credit),0) ELSE COALESCE(sum(l.credit-l.debit),0) END balance FROM ledger_accounts a JOIN journal_lines l ON l.ledger_account_id=a.id JOIN journal_entries e ON e.id=l.journal_entry_id WHERE ${journalFilter} AND a.account_type IN('asset','liability','equity') GROUP BY a.id ORDER BY a.account_type,a.code` },
  "accounting/cash-flow": { title: "Cash flow", sql: `SELECT m.business_date,a.name account,m.movement_type,m.description,m.amount,m.source_type FROM financial_movements m JOIN financial_accounts a ON a.id=m.account_id WHERE m.company_id=$1 AND ($2::date IS NULL OR m.business_date >= $2) AND ($3::date IS NULL OR m.business_date <= $3) ORDER BY m.business_date DESC,m.created_at DESC` },
  "accounting/aging": { title: "Customer aging", sql: `SELECT c.code,c.name,i.invoice_number,i.invoice_date,i.due_date,i.remaining_amount,CASE WHEN current_date<=COALESCE(i.due_date,current_date) THEN 'current' WHEN current_date-i.due_date<=30 THEN '1-30' WHEN current_date-i.due_date<=60 THEN '31-60' WHEN current_date-i.due_date<=90 THEN '61-90' ELSE '90+' END aging_bucket FROM sales_invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE ${invoiceFilter} AND i.remaining_amount>0 ORDER BY i.due_date NULLS LAST` },
  "accounting/tax": { title: "Tax report", sql: `SELECT i.invoice_date,i.invoice_number,COALESCE(c.name,i.customer_name,'Walk-in') customer,i.subtotal taxable_amount,i.tax_amount tax,i.total FROM sales_invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE ${invoiceFilter} ORDER BY i.invoice_date DESC` },

  "customers/statement": { title: "Customer statement", sql: `SELECT c.code,c.name,'invoice' transaction_type,i.invoice_number reference,i.invoice_date business_date,i.total debit,i.paid_amount credit,i.remaining_amount balance FROM customers c JOIN sales_invoices i ON i.customer_id=c.id WHERE ${invoiceFilter} ORDER BY c.code,i.invoice_date` },
  "customers/balances": { title: "Customer balances", sql: `SELECT code,name,name_ar,total_sales,total_paid,balance,credit_limit,GREATEST(balance-credit_limit,0) over_limit FROM customers WHERE company_id=$1 ORDER BY balance DESC` },
  "customers/analysis": { title: "Customer analysis", sql: `SELECT c.code,c.name,count(i.id)::int invoices,COALESCE(sum(i.total),0) sales,COALESCE(avg(i.total),0) average_invoice,max(i.invoice_date) last_sale FROM customers c LEFT JOIN sales_invoices i ON i.customer_id=c.id AND ($2::date IS NULL OR i.invoice_date >= $2) AND ($3::date IS NULL OR i.invoice_date <= $3) WHERE c.company_id=$1 GROUP BY c.id ORDER BY sales DESC` },
  "customers/top": { title: "Top customers", sql: `SELECT c.code,c.name,count(i.id)::int invoices,COALESCE(sum(i.total),0) sales,COALESCE(sum(i.paid_amount),0) paid FROM customers c JOIN sales_invoices i ON i.customer_id=c.id WHERE ${invoiceFilter} GROUP BY c.id ORDER BY sales DESC LIMIT 25` },

  "purchases/by-supplier": { title: "Purchases by supplier", sql: `SELECT s.code,s.name,count(o.id)::int orders,COALESCE(sum(o.total),0) ordered_total,COALESCE(sum(a.amount) FILTER(WHERE a.status='open'),0) open_accruals FROM suppliers s LEFT JOIN purchase_orders o ON o.supplier_id=s.id AND ($2::date IS NULL OR o.order_date >= $2) AND ($3::date IS NULL OR o.order_date <= $3) LEFT JOIN supplier_accruals a ON a.supplier_id=s.id WHERE s.company_id=$1 GROUP BY s.id ORDER BY ordered_total DESC` },
  "purchases/pending": { title: "Pending purchase orders", sql: `SELECT o.order_number,o.order_date,o.expected_date,s.name supplier,w.name warehouse,o.status,o.total,COALESCE(sum(x.ordered_quantity-x.received_quantity),0) remaining_quantity FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id JOIN warehouses w ON w.id=o.warehouse_id JOIN purchase_order_items x ON x.purchase_order_id=o.id WHERE ${purchaseFilter} AND o.status NOT IN('received','closed','cancelled','rejected') GROUP BY o.id,s.name,w.name ORDER BY o.expected_date NULLS LAST` },
  "purchases/prices": { title: "Purchase price analysis", sql: `SELECT p.sku,p.name,min(x.unit_price) minimum_price,max(x.unit_price) maximum_price,avg(x.unit_price) average_price,max(o.order_date) latest_order_date FROM purchase_order_items x JOIN purchase_orders o ON o.id=x.purchase_order_id JOIN products p ON p.id=x.product_id WHERE ${purchaseFilter} GROUP BY p.id ORDER BY p.name` },
  "purchases/supplier-performance": { title: "Supplier performance", sql: `SELECT s.code,s.name,s.rating,count(o.id)::int orders,count(o.id) FILTER(WHERE o.status IN('received','closed'))::int completed_orders,COALESCE(avg(gr.receipt_date-o.expected_date) FILTER(WHERE o.expected_date IS NOT NULL),0) average_days_late,COALESCE(sum(o.total),0) total_value FROM suppliers s LEFT JOIN purchase_orders o ON o.supplier_id=s.id AND ($2::date IS NULL OR o.order_date >= $2) AND ($3::date IS NULL OR o.order_date <= $3) LEFT JOIN goods_receipts gr ON gr.purchase_order_id=o.id WHERE s.company_id=$1 GROUP BY s.id ORDER BY completed_orders DESC,total_value DESC` },

  "hr/attendance": { title: "Attendance log", sql: `SELECT r.business_date,u.name employee,b.name branch,s.name shift,r.check_in_at,r.check_out_at,r.worked_minutes,r.late_minutes,r.early_leave_minutes,r.status FROM attendance_records r JOIN users u ON u.id=r.user_id LEFT JOIN branches b ON b.id=r.branch_id LEFT JOIN attendance_shifts s ON s.id=r.shift_id WHERE r.company_id=$1 AND ($2::date IS NULL OR r.business_date >= $2) AND ($3::date IS NULL OR r.business_date <= $3) ORDER BY r.business_date DESC,u.name` },
  "hr/payroll": { title: "Payroll summary", sql: `SELECT r.year,r.month,r.status,p.employee_code,p.employee_name employee,p.base_salary,p.overtime_pay,p.allowances,p.deductions,p.gross_salary,p.net_salary FROM payroll_runs r JOIN payroll_payslips p ON p.payroll_run_id=r.id WHERE r.company_id=$1 AND ($2::date IS NULL OR make_date(r.year,r.month,1)>=$2) AND ($3::date IS NULL OR make_date(r.year,r.month,1)<=$3) ORDER BY r.year DESC,r.month DESC,p.employee_code` },
  "hr/overtime": { title: "Overtime report", sql: `SELECT r.business_date,u.name employee,s.name shift,r.worked_minutes,GREATEST(COALESCE(r.worked_minutes,0)-480,0) overtime_minutes FROM attendance_records r JOIN users u ON u.id=r.user_id LEFT JOIN attendance_shifts s ON s.id=r.shift_id WHERE r.company_id=$1 AND ($2::date IS NULL OR r.business_date >= $2) AND ($3::date IS NULL OR r.business_date <= $3) AND COALESCE(r.worked_minutes,0)>480 ORDER BY r.business_date DESC,overtime_minutes DESC`, note: "Overtime is estimated above eight worked hours until shift-specific payroll rules are configured." },
  "hr/leaves": { title: "Leave balance", sql: `SELECT p.employee_code,u.name employee,d.name department,'not_tracked' leave_status FROM hr_employee_profiles p JOIN users u ON u.id=p.user_id LEFT JOIN hr_departments d ON d.id=p.department_id WHERE p.company_id=$1 AND p.employment_status='active' ORDER BY p.employee_code`, note: "Leave entitlements and requests are not yet stored; balances cannot be calculated without inventing data." },
};

const filterSchema = z.object({ from: z.string().date().optional(), to: z.string().date().optional(), format: z.enum(["json", "csv"]).default("json") }).refine((v) => !v.from || !v.to || v.from <= v.to, { message: "From date must not be after to date" });
function csvCell(value: unknown) { const text = value == null ? "" : String(value); return `"${text.replaceAll('"', '""')}"`; }

export const reportsRouter = Router();
reportsRouter.get("/:domain/:report", authorizeAny("reports.read", "reports.view"), async (req, res) => {
  const key = `${req.params.domain}/${req.params.report}`;
  const definition = reports[key];
  if (!definition) throw new HttpError(404, "REPORT_NOT_FOUND", "Report not found");
  const filters = validate(filterSchema, req.query);
  const parameterCount = Math.max(...[...definition.sql.matchAll(/\$(\d+)/g)].map((match) => Number(match[1])));
  const parameters = [req.auth!.companyId, filters.from ?? null, filters.to ?? null].slice(0, parameterCount);
  const result = await query<Record<string, unknown>>(definition.sql, parameters);
  const rows = serializeRows(result.rows);
  if (filters.format === "csv") {
    const columns = rows.length ? Object.keys(rows[0]) : [];
    const csv = [columns.map(csvCell).join(","), ...rows.map((row) => columns.map((column) => csvCell(row[column])).join(","))].join("\r\n");
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${key.replace("/", "-")}.csv"`);
    return res.send(`\uFEFF${csv}`);
  }
  res.json({ data: { key, title: definition.title, note: definition.note, generatedAt: new Date().toISOString(), currency: "EGP", filters: { from: filters.from ?? null, to: filters.to ?? null }, rows } });
});
