import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Banknote, CheckCircle2, Loader2, Plus, RefreshCw, WalletCards } from "lucide-react";
import { useTranslation } from "react-i18next";
import { AppLayout } from "@/components/layout/AppLayout";
import { apiRequest } from "@erp/shared-frontend-data-access";
import { useAuth } from "@/lib/auth";

type Run={id:string;year:number;month:number;status:"draft"|"approved"|"paid";employeeCount:number;totalGross:number;totalDeductions:number;totalNet:number;approvedAt?:string;paidAt?:string};
type Slip={id:string;employeeCode:string;employeeName:string;baseSalary:number;workingDays:number;overtimeHours:number;overtimePay:number;allowances:number;deductions:number;grossSalary:number;netSalary:number;notes:string};
type Detail={run:Run;payslips:Slip[]}; type Account={id:string;name:string;balance:number;currency:string;isActive:boolean};
const money=(value:number,ar:boolean)=>new Intl.NumberFormat(ar?"ar-EG":"en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:2}).format(Number(value||0));

export default function PayrollPage(){
  const {i18n}=useTranslation(),ar=i18n.language.startsWith("ar"),{can}=useAuth();
  const canProcess=can("payroll.write")||can("payroll.process"),canApprove=can("payroll.write")||can("payroll.approve");
  const [runs,setRuns]=useState<Run[]>([]),[detail,setDetail]=useState<Detail|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async(selectedId?:string)=>{try{const [rows,financial]=await Promise.all([apiRequest<Run[]>("/payroll/runs"),apiRequest<Account[]>("/payroll/accounts").catch(()=>[])]);setRuns(rows);setAccounts(financial.filter(x=>x.isActive));const id=selectedId??rows[0]?.id;if(id)setDetail(await apiRequest<Detail>(`/payroll/runs/${id}`));else setDetail(null);}catch(e){setMessage(e instanceof Error?e.message:"Failed");}},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const run=await apiRequest<Run>("/payroll/runs",{method:"POST",body:JSON.stringify({year:Number(f.get("year")),month:Number(f.get("month"))})});await load(run.id);setMessage(ar?"تم إنشاء دورة الرواتب وربط الموظفين والحضور.":"Payroll run created from employees and attendance.");}catch(error){setMessage(error instanceof Error?error.message:"Failed");}finally{setBusy(false);}}
  async function saveSlip(e:FormEvent<HTMLFormElement>,slip:Slip){e.preventDefault();if(!detail)return;setBusy(true);const f=new FormData(e.currentTarget);try{await apiRequest(`/payroll/runs/${detail.run.id}/payslips/${slip.id}`,{method:"PATCH",body:JSON.stringify({allowances:Number(f.get("allowances")),deductions:Number(f.get("deductions")),notes:String(f.get("notes")??"")})});await load(detail.run.id);setMessage(ar?"تم تحديث كشف الموظف.":"Payslip updated.");}catch(error){setMessage(error instanceof Error?error.message:"Failed");}finally{setBusy(false);}}
  async function action(kind:"approve"|"pay"){if(!detail)return;setBusy(true);try{await apiRequest(`/payroll/runs/${detail.run.id}/${kind}`,{method:"POST",body:JSON.stringify(kind==="pay"?{accountId}:{})});await load(detail.run.id);setMessage(kind==="approve"?(ar?"تم اعتماد دورة الرواتب.":"Payroll approved."):(ar?"تم تسجيل دفع الرواتب.":"Payroll payment recorded."));}catch(error){setMessage(error instanceof Error?error.message:"Failed");}finally{setBusy(false);}}
  const now=new Date();
  return <AppLayout><main className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-primary-600"><WalletCards className="h-5 w-5"/>{ar?"الموارد البشرية":"Human resources"}</div><h1 className="text-2xl font-bold">{ar?"نظام الرواتب":"Payroll system"}</h1><p className="mt-1 text-navy-500">{ar?"دورات الرواتب وكشوف الموظفين والاعتماد والدفع":"Payroll runs, employee payslips, approval and payment"}</p></div>{canProcess&&<form onSubmit={e=>void create(e)} className="flex flex-wrap items-end gap-2"><label className="text-sm">{ar?"السنة":"Year"}<input className="input mt-1 w-28" name="year" type="number" defaultValue={now.getFullYear()} min="2000" max="2200"/></label><label className="text-sm">{ar?"الشهر":"Month"}<input className="input mt-1 w-24" name="month" type="number" defaultValue={now.getMonth()+1} min="1" max="12"/></label><button disabled={busy} className="btn btn-primary"><Plus className="h-4 w-4"/>{ar?"إنشاء دورة":"New run"}</button></form>}</header>
    {message&&<div role="status" className="rounded-xl bg-primary-50 p-3 text-primary-700">{message}</div>}
    <section className="grid gap-4 md:grid-cols-4"><Stat label={ar?"الدورات":"Runs"} value={String(runs.length)}/><Stat label={ar?"الموظفون":"Employees"} value={String(detail?.run.employeeCount??0)}/><Stat label={ar?"الإجمالي":"Gross"} value={money(detail?.run.totalGross??0,ar)}/><Stat label={ar?"الصافي":"Net"} value={money(detail?.run.totalNet??0,ar)}/></section>
    <div className="grid gap-5 xl:grid-cols-[280px_1fr]"><aside className="card overflow-hidden"><h2 className="border-b p-4 font-bold">{ar?"دورات الرواتب":"Payroll runs"}</h2>{runs.map(run=><button key={run.id} onClick={()=>void load(run.id)} className={`flex w-full items-center justify-between border-b p-4 text-start ${detail?.run.id===run.id?"bg-primary-50":"hover:bg-navy-50"}`}><span><strong>{String(run.month).padStart(2,"0")}-{run.year}</strong><small className="block text-navy-500">{money(run.totalNet,ar)}</small></span><Status status={run.status} ar={ar}/></button>)}{!runs.length&&<p className="p-6 text-center text-navy-500">{ar?"لا توجد دورات بعد.":"No payroll runs yet."}</p>}</aside>
      <section className="space-y-4">{detail&&<><div className="card flex flex-wrap items-center justify-between gap-3 p-4"><div><h2 className="font-bold">{ar?"دورة":"Payroll"} {String(detail.run.month).padStart(2,"0")}-{detail.run.year}</h2><Status status={detail.run.status} ar={ar}/></div><div className="flex flex-wrap items-end gap-2">{detail.run.status==="draft"&&canApprove&&<button disabled={busy} className="btn btn-primary" onClick={()=>void action("approve")}><CheckCircle2 className="h-4 w-4"/>{ar?"اعتماد":"Approve"}</button>}{detail.run.status==="approved"&&canApprove&&<><label className="text-sm">{ar?"حساب الدفع":"Payment account"}<select className="select mt-1" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">{ar?"اختر حسابًا":"Select account"}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} — {money(a.balance,ar)}</option>)}</select></label><button disabled={busy||!accountId} className="btn btn-primary" onClick={()=>void action("pay")}><Banknote className="h-4 w-4"/>{ar?"تسجيل الدفع":"Record payment"}</button></>}<button className="btn btn-ghost" onClick={()=>void load(detail.run.id)}><RefreshCw className="h-4 w-4"/></button></div></div>
      <div className="card overflow-x-auto"><table className="table"><thead><tr><th>{ar?"الموظف":"Employee"}</th><th>{ar?"الأساسي":"Base"}</th><th>{ar?"أيام العمل":"Days"}</th><th>{ar?"الإضافي":"Overtime"}</th><th>{ar?"البدلات":"Allowances"}</th><th>{ar?"الخصومات":"Deductions"}</th>{detail.run.status==="draft"&&canProcess&&<th>{ar?"إجراء":"Action"}</th>}<th>{ar?"الصافي":"Net"}</th></tr></thead><tbody>{detail.payslips.map(s=><tr key={s.id}><td><strong>{s.employeeName}</strong><small className="block text-navy-500">{s.employeeCode}</small></td><td>{money(s.baseSalary,ar)}</td><td>{s.workingDays}</td><td>{Number(s.overtimeHours).toFixed(2)}h<br/><small>{money(s.overtimePay,ar)}</small></td>{detail.run.status==="draft"&&canProcess?<PayslipInputs slip={s} ar={ar} busy={busy} save={saveSlip}/>:<><td>{money(s.allowances,ar)}</td><td>{money(s.deductions,ar)}</td></>}<td className="font-bold">{money(s.netSalary,ar)}</td></tr>)}</tbody></table>{!detail.payslips.length&&<p className="p-8 text-center text-navy-500">{ar?"لا يوجد موظفون نشطون في هذه الدورة.":"No active employees in this run."}</p>}</div></>}</section></div>
    {busy&&<div className="fixed bottom-5 end-5 rounded-xl bg-navy-900 p-3 text-white"><Loader2 className="h-5 w-5 animate-spin"/></div>}
  </main></AppLayout>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat-card"><p className="stat-label">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
function Status({status,ar}:{status:Run["status"];ar:boolean}){const text={draft:ar?"مسودة":"Draft",approved:ar?"معتمد":"Approved",paid:ar?"مدفوع":"Paid"}[status];return <span className={`badge ${status==="paid"?"badge-success":status==="approved"?"badge-primary":"badge-gray"}`}>{text}</span>}
function PayslipInputs({slip,ar,busy,save}:{slip:Slip;ar:boolean;busy:boolean;save:(e:FormEvent<HTMLFormElement>,s:Slip)=>Promise<void>}){return <><td><form id={`slip-${slip.id}`} onSubmit={e=>void save(e,slip)}><input aria-label={ar?"البدلات":"Allowances"} className="input w-28" name="allowances" type="number" min="0" step="0.01" defaultValue={slip.allowances}/><input type="hidden" name="notes" value={slip.notes}/></form></td><td><input form={`slip-${slip.id}`} aria-label={ar?"الخصومات":"Deductions"} className="input w-28" name="deductions" type="number" min="0" step="0.01" defaultValue={slip.deductions}/></td><td><button form={`slip-${slip.id}`} disabled={busy} className="btn btn-secondary btn-sm">{ar?"حفظ":"Save"}</button></td></>}
