import { useCallback, useEffect, useMemo, useState } from 'react';
import { Boxes, RefreshCw, TrendingUp } from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { apiGet } from '@/lib/api-client';
import { useTranslation } from 'react-i18next';

type Balance = { companyId: string; warehouseId: string; productId: string; sku: string; productName: string; warehouseCode: string; warehouseName: string; onHand: string; reserved: string; available: string; averageCost: string };
type Movement = { id: string; productName: string; sku: string; warehouseCode: string; movementType: string; quantity: string; unitCost: string; businessDate: string; sourceType: string };

export default function InventoryPage() {
  const { i18n } = useTranslation(); const ar = i18n.language.startsWith('ar');
  const [balances, setBalances] = useState<Balance[]>([]); const [movements, setMovements] = useState<Movement[]>([]); const [tab, setTab] = useState<'balances' | 'movements'>('balances'); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [stock, history] = await Promise.all([apiGet<Balance[]>('/inventory/availability'), apiGet<Movement[]>('/inventory/movements')]); setBalances(stock); setMovements(history); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed'); } }, []);
  // The async request is the external synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const stats = useMemo(() => ({ products: new Set(balances.map((item) => item.productId)).size, warehouses: new Set(balances.map((item) => item.warehouseId)).size, units: balances.reduce((sum, item) => sum + Number(item.onHand), 0) }), [balances]);
  return <AppLayout><div className="mb-6 flex items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-navy-900 dark:text-white">{ar ? 'المخزون' : 'Inventory'}</h1><p className="text-navy-500">{ar ? 'أرصدة وحركات المخازن من سجل المخزون' : 'Warehouse balances and immutable stock movements'}</p></div><button className="btn btn-secondary btn-sm" onClick={() => void load()}><RefreshCw className="h-4 w-4" />{ar ? 'تحديث' : 'Refresh'}</button></div>{error && <div className="mb-4 rounded-lg bg-danger-50 p-3 text-danger-700">{error}</div>}<div className="mb-6 grid gap-4 sm:grid-cols-3"><div className="stat-card"><p className="stat-label">{ar ? 'المنتجات' : 'Products'}</p><p className="stat-value">{stats.products}</p></div><div className="stat-card"><p className="stat-label">{ar ? 'المخازن' : 'Warehouses'}</p><p className="stat-value">{stats.warehouses}</p></div><div className="stat-card"><p className="stat-label">{ar ? 'الكمية المتاحة' : 'On hand'}</p><p className="stat-value">{stats.units.toFixed(3)}</p></div></div><div className="mb-4 flex gap-2"><button className={`btn btn-sm ${tab === 'balances' ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setTab('balances')}><Boxes className="h-4 w-4" />{ar ? 'الأرصدة' : 'Balances'}</button><button className={`btn btn-sm ${tab === 'movements' ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setTab('movements')}><TrendingUp className="h-4 w-4" />{ar ? 'الحركات' : 'Movements'}</button></div><div className="card overflow-x-auto">{tab === 'balances' ? <table className="table min-w-[800px]"><thead><tr><th>SKU</th><th>{ar ? 'المنتج' : 'Product'}</th><th>{ar ? 'المخزن' : 'Warehouse'}</th><th>{ar ? 'فعلي' : 'On hand'}</th><th>{ar ? 'محجوز' : 'Reserved'}</th><th>{ar ? 'متاح' : 'Available'}</th><th>{ar ? 'متوسط التكلفة' : 'Average cost'}</th></tr></thead><tbody>{balances.map((item) => <tr key={`${item.warehouseId}-${item.productId}`}><td>{item.sku}</td><td>{item.productName}</td><td>{item.warehouseCode} — {item.warehouseName}</td><td>{item.onHand}</td><td>{item.reserved}</td><td className="font-semibold">{item.available}</td><td>{item.averageCost} EGP</td></tr>)}</tbody></table> : <table className="table min-w-[850px]"><thead><tr><th>{ar ? 'التاريخ' : 'Date'}</th><th>SKU</th><th>{ar ? 'المنتج' : 'Product'}</th><th>{ar ? 'المخزن' : 'Warehouse'}</th><th>{ar ? 'الحركة' : 'Movement'}</th><th>{ar ? 'الكمية' : 'Quantity'}</th><th>{ar ? 'المصدر' : 'Source'}</th></tr></thead><tbody>{movements.map((item) => <tr key={item.id}><td>{item.businessDate}</td><td>{item.sku}</td><td>{item.productName}</td><td>{item.warehouseCode}</td><td><span className="badge badge-success">{item.movementType}</span></td><td>{item.quantity}</td><td>{item.sourceType}</td></tr>)}</tbody></table>}{!(tab === 'balances' ? balances.length : movements.length) && <div className="empty-state"><Boxes className="empty-state-icon" /><p>{ar ? 'لا توجد بيانات مخزون' : 'No inventory data yet'}</p></div>}</div></AppLayout>;
}
