import { Router } from 'express';
import { z } from 'zod';
import { query,transaction } from '../../db/client.js';
import { HttpError,validate } from '../../lib/http.js';
import { getActiveStore,type StoreRow } from './store.js';

const tokenSchema=z.uuid();const itemSchema=z.object({productId:z.uuid(),variantId:z.uuid().optional(),quantity:z.number().int().min(1).max(99).default(1)});const quantitySchema=z.object({quantity:z.number().int().min(1).max(99)});
async function cartIdentity(store:StoreRow,token:string){const cart=(await query<{id:string;token:string;currency:string}>(`SELECT id,token::text,currency FROM storefront_carts WHERE company_id=$1 AND token=$2 AND status='active' AND expires_at>now()`,[store.company_id,validate(tokenSchema,token)])).rows[0];if(!cart)throw new HttpError(404,'CART_NOT_FOUND','Cart not found or expired');return cart;}
async function snapshot(store:StoreRow,token:string){const cart=await cartIdentity(store,token);const rows=await query(`SELECT ci.id,ci.product_id,ci.variant_id,ci.quantity,p.slug,p.name,p.name_ar,COALESCE(v.sku,p.sku) sku,COALESCE(v.selling_price,p.selling_price) unit_price,COALESCE(v.stock_quantity,inventory.available_stock,p.total_stock) stock_quantity,p.tax_rate,p.type,pm.thumbnail_url,pm.url image_url
 FROM storefront_cart_items ci JOIN products p ON p.id=ci.product_id AND p.company_id=$1 LEFT JOIN product_variants v ON v.id=ci.variant_id AND v.company_id=$1
 LEFT JOIN LATERAL(SELECT SUM(available) available_stock FROM inventory_balances WHERE company_id=$1 AND product_id=p.id)inventory ON true
 LEFT JOIN LATERAL(SELECT url,thumbnail_url FROM product_media WHERE company_id=$1 AND product_id=p.id AND media_type='image' ORDER BY position,id LIMIT 1)pm ON true WHERE ci.cart_id=$2 ORDER BY ci.created_at`,[store.company_id,cart.id]);
 const lines=rows.rows.map(r=>{const price=Number(r.unit_price),quantity=Number(r.quantity),subtotal=price*quantity,tax=subtotal*Number(r.tax_rate)/100,stock=Number(r.stock_quantity);return{id:r.id,productId:r.product_id,variantId:r.variant_id,slug:r.slug,name:r.name,nameAr:r.name_ar,sku:r.sku,imageUrl:r.thumbnail_url||r.image_url,quantity,unitPrice:price,lineSubtotal:Number(subtotal.toFixed(2)),taxAmount:Number(tax.toFixed(2)),availability:r.type==='service'?'in_stock':stock<=0?'out_of_stock':stock<=quantity?'low_stock':'in_stock',maxQuantity:r.type==='service'?99:Math.max(0,Math.min(99,Math.floor(stock)))};});
 const subtotal=lines.reduce((s,l)=>s+l.lineSubtotal,0),taxTotal=lines.reduce((s,l)=>s+l.taxAmount,0);return{token:cart.token,currency:cart.currency,lines,itemCount:lines.reduce((s,l)=>s+l.quantity,0),subtotal:Number(subtotal.toFixed(2)),taxTotal:Number(taxTotal.toFixed(2)),shippingTotal:0,discountTotal:0,total:Number((subtotal+taxTotal).toFixed(2))};
}
export const cartRouter=Router();
cartRouter.post('/',async(_req,res)=>{const store=await getActiveStore();const cart=(await query<{token:string}>(`INSERT INTO storefront_carts(company_id,currency) VALUES($1,$2) RETURNING token::text`,[store.company_id,store.currency])).rows[0];res.status(201).json({data:await snapshot(store,cart.token)});});
cartRouter.get('/',async(req,res)=>{const store=await getActiveStore();res.json({data:await snapshot(store,req.header('x-cart-token')||'')});});
cartRouter.post('/items',async(req,res)=>{const store=await getActiveStore(),cart=await cartIdentity(store,req.header('x-cart-token')||''),input=validate(itemSchema,req.body);const product=(await query<{id:string;type:string;available_stock:string;has_variants:boolean}>(`SELECT p.id,p.type,COALESCE((SELECT SUM(available) FROM inventory_balances WHERE company_id=p.company_id AND product_id=p.id),p.total_stock)available_stock,EXISTS(SELECT 1 FROM product_variants WHERE company_id=p.company_id AND product_id=p.id AND is_active=true)has_variants FROM products p WHERE p.id=$1 AND p.company_id=$2 AND p.is_active=true AND p.storefront_visible=true AND p.commerce_status='active' AND p.published_at<=now()`,[input.productId,store.company_id])).rows[0];if(!product)throw new HttpError(404,'PRODUCT_NOT_AVAILABLE','Product is not available');if(product.has_variants&&!input.variantId)throw new HttpError(400,'VARIANT_REQUIRED','Select a product option');let stock=Number(product.available_stock);if(input.variantId){const variant=(await query<{stock_quantity:string}>(`SELECT stock_quantity FROM product_variants WHERE id=$1 AND product_id=$2 AND company_id=$3 AND is_active=true`,[input.variantId,input.productId,store.company_id])).rows[0];if(!variant)throw new HttpError(400,'INVALID_VARIANT','Selected option is unavailable');stock=Math.min(stock,Number(variant.stock_quantity));}if(product.type!=='service'&&stock<input.quantity)throw new HttpError(409,'INSUFFICIENT_STOCK','Requested quantity is unavailable');await transaction(async client=>{const existing=(await client.query<{id:string;quantity:number}>(`SELECT id,quantity FROM storefront_cart_items WHERE cart_id=$1 AND product_id=$2 AND variant_id IS NOT DISTINCT FROM $3`,[cart.id,input.productId,input.variantId??null])).rows[0];const next=(existing?.quantity??0)+input.quantity;if(product.type!=='service'&&next>stock)throw new HttpError(409,'INSUFFICIENT_STOCK','Requested quantity is unavailable');if(existing)await client.query(`UPDATE storefront_cart_items SET quantity=$2,updated_at=now() WHERE id=$1`,[existing.id,next]);else await client.query(`INSERT INTO storefront_cart_items(cart_id,product_id,variant_id,quantity)VALUES($1,$2,$3,$4)`,[cart.id,input.productId,input.variantId??null,input.quantity]);await client.query(`UPDATE storefront_carts SET updated_at=now(),expires_at=now()+interval '30 days' WHERE id=$1`,[cart.id]);});res.status(201).json({data:await snapshot(store,cart.token)});});
cartRouter.patch('/items/:id',async(req,res)=>{const store=await getActiveStore(),cart=await cartIdentity(store,req.header('x-cart-token')||''),{quantity}=validate(quantitySchema,req.body);const line=(await query<{stock:string;type:string}>(`SELECT LEAST(COALESCE(v.stock_quantity,p.total_stock),COALESCE((SELECT SUM(available) FROM inventory_balances WHERE company_id=p.company_id AND product_id=p.id),p.total_stock))stock,p.type FROM storefront_cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN product_variants v ON v.id=ci.variant_id WHERE ci.id=$1 AND ci.cart_id=$2`,[req.params.id,cart.id])).rows[0];if(!line)throw new HttpError(404,'CART_ITEM_NOT_FOUND','Cart item not found');if(line.type!=='service'&&quantity>Number(line.stock))throw new HttpError(409,'INSUFFICIENT_STOCK','Requested quantity is unavailable');await query(`UPDATE storefront_cart_items SET quantity=$3,updated_at=now() WHERE id=$1 AND cart_id=$2`,[req.params.id,cart.id,quantity]);res.json({data:await snapshot(store,cart.token)});});
cartRouter.delete('/items/:id',async(req,res)=>{const store=await getActiveStore(),cart=await cartIdentity(store,req.header('x-cart-token')||'');const removed=await query(`DELETE FROM storefront_cart_items WHERE id=$1 AND cart_id=$2 RETURNING id`,[req.params.id,cart.id]);if(!removed.rowCount)throw new HttpError(404,'CART_ITEM_NOT_FOUND','Cart item not found');res.json({data:await snapshot(store,cart.token)});});

export const checkoutRouter=Router();
checkoutRouter.post('/validate',async(req,res)=>{const store=await getActiveStore(),token=req.header('x-cart-token')||'',input=validate(z.object({shippingMethodId:z.uuid(),paymentMethodId:z.uuid()}),req.body),cart=await snapshot(store,token);const[shipping,payment]=await Promise.all([query(`SELECT id,name,name_ar,description,fee,configuration FROM shipping_methods WHERE id=$1 AND company_id=$2 AND is_enabled=true`,[input.shippingMethodId,store.company_id]),query(`SELECT id,code,name,name_ar,instructions,configuration FROM payment_methods WHERE id=$1 AND company_id=$2 AND is_enabled=true`,[input.paymentMethodId,store.company_id])]);const errors:string[]=[];if(!cart.lines.length)errors.push('Cart is empty');if(cart.lines.some(l=>l.availability==='out_of_stock'||l.quantity>l.maxQuantity))errors.push('One or more items are unavailable');if(!shipping.rows[0])errors.push('Shipping method is unavailable');if(!payment.rows[0])errors.push('Payment method is unavailable');const s=shipping.rows[0],p=payment.rows[0],shippingTotal=s?Number(s.fee):0;res.json({data:{ready:errors.length===0,errors,cart:{...cart,shippingTotal,total:Number((cart.total+shippingTotal).toFixed(2))},shippingMethod:s?{id:s.id,name:s.name,nameAr:s.name_ar,description:s.description,fee:shippingTotal,configuration:s.configuration}:undefined,paymentMethod:p?{id:p.id,code:p.code,name:p.name,nameAr:p.name_ar,instructions:p.instructions,configuration:p.configuration}:undefined}});});
