import { Router } from "express";
import { z } from "zod";
import { query, transaction } from "../../db/client.js";
import { HttpError, validate } from "../../lib/http.js";
import { serializeRow, serializeRows } from "../../lib/rows.js";
import { authorizeAny } from "../auth/middleware.js";
import { appendAuditEvent } from "../audit/routes.js";

const periodSchema=z.object({year:z.number().int().min(2000).max(2200),month:z.number().int().min(1).max(12)});
const adjustmentSchema=z.object({allowances:z.number().min(0).max(100000000),deductions:z.number().min(0).max(100000000),notes:z.string().max(500).default("")});
export const payrollRouter=Router();
const read=authorizeAny("payroll.read","payroll.view","payroll.process","payroll.approve");
const process=authorizeAny("payroll.write","payroll.process");
const approve=authorizeAny("payroll.write","payroll.approve");

async function runForCompany(id:string,companyId:string){const row=(await query("SELECT * FROM payroll_runs WHERE id=$1 AND company_id=$2",[id,companyId])).rows[0];if(!row)throw new HttpError(404,"PAYROLL_RUN_NOT_FOUND","Payroll run not found");return row;}
async function recalculate(client:{query:(sql:string,params?:unknown[])=>Promise<{rows:Record<string,unknown>[]}>},runId:string){
  await client.query(`UPDATE payroll_payslips SET gross_salary=round(base_salary+overtime_pay+allowances,2),net_salary=GREATEST(0,round(base_salary+overtime_pay+allowances-deductions,2)),updated_at=now() WHERE payroll_run_id=$1`,[runId]);
  await client.query(`UPDATE payroll_runs r SET employee_count=x.employee_count,total_gross=x.total_gross,total_deductions=x.total_deductions,total_net=x.total_net,updated_at=now() FROM(SELECT count(*)::int employee_count,COALESCE(sum(gross_salary),0) total_gross,COALESCE(sum(deductions),0) total_deductions,COALESCE(sum(net_salary),0) total_net FROM payroll_payslips WHERE payroll_run_id=$1)x WHERE r.id=$1`,[runId]);
}

payrollRouter.get("/runs",read,async(req,res)=>res.json({data:serializeRows((await query("SELECT * FROM payroll_runs WHERE company_id=$1 ORDER BY year DESC,month DESC",[req.auth!.companyId])).rows)}));
payrollRouter.get("/accounts",approve,async(req,res)=>res.json({data:serializeRows((await query("SELECT id,name,account_type,currency,balance,is_active FROM financial_accounts WHERE company_id=$1 AND is_active=true ORDER BY name",[req.auth!.companyId])).rows)}));
payrollRouter.get("/runs/:id",read,async(req,res)=>{const run=await runForCompany(String(req.params.id),req.auth!.companyId);const slips=(await query("SELECT * FROM payroll_payslips WHERE payroll_run_id=$1 AND company_id=$2 ORDER BY employee_code",[req.params.id,req.auth!.companyId])).rows;res.json({data:{run:serializeRow(run),payslips:serializeRows(slips)}});});
payrollRouter.post("/runs",process,async(req,res)=>{
  const input=validate(periodSchema,req.body),start=`${input.year}-${String(input.month).padStart(2,"0")}-01`;
  const run=await transaction(async client=>{
    const created=(await client.query(`INSERT INTO payroll_runs(company_id,year,month,created_by)VALUES($1,$2,$3,$4)RETURNING *`,[req.auth!.companyId,input.year,input.month,req.auth!.userId])).rows[0];
    await client.query(`INSERT INTO payroll_payslips(payroll_run_id,company_id,employee_id,employee_code,employee_name,base_salary,working_days,overtime_hours,overtime_pay,gross_salary,net_salary)
      SELECT $1,p.company_id,p.user_id,p.employee_code,u.name,p.base_salary,COALESCE(a.working_days,0),COALESCE(a.overtime_minutes,0)/60.0,round((p.base_salary/240.0)*(COALESCE(a.overtime_minutes,0)/60.0)*1.5,2),p.base_salary+round((p.base_salary/240.0)*(COALESCE(a.overtime_minutes,0)/60.0)*1.5,2),p.base_salary+round((p.base_salary/240.0)*(COALESCE(a.overtime_minutes,0)/60.0)*1.5,2)
      FROM hr_employee_profiles p JOIN users u ON u.id=p.user_id LEFT JOIN LATERAL(SELECT count(*)::int working_days,sum(GREATEST(COALESCE(r.worked_minutes,0)-480,0)) overtime_minutes FROM attendance_records r WHERE r.user_id=p.user_id AND r.business_date>=$2::date AND r.business_date<($2::date+interval '1 month'))a ON true WHERE p.company_id=$3 AND p.employment_status='active' AND u.is_active=true`,[created.id,start,req.auth!.companyId]);
    await recalculate(client,created.id);
    const complete=(await client.query("SELECT * FROM payroll_runs WHERE id=$1",[created.id])).rows[0];
    await appendAuditEvent(client,{tenantId:req.auth!.tenantId,companyId:req.auth!.companyId,actorUserId:req.auth!.userId,action:"payroll.run_created",entityType:"payroll_run",entityId:created.id,after:complete});return complete;
  });res.status(201).json({data:serializeRow(run)});
});
payrollRouter.patch("/runs/:runId/payslips/:id",process,async(req,res)=>{const i=validate(adjustmentSchema,req.body);const row=await transaction(async client=>{const run=(await client.query("SELECT * FROM payroll_runs WHERE id=$1 AND company_id=$2 FOR UPDATE",[req.params.runId,req.auth!.companyId])).rows[0];if(!run)throw new HttpError(404,"PAYROLL_RUN_NOT_FOUND","Payroll run not found");if(run.status!=="draft")throw new HttpError(409,"PAYROLL_LOCKED","Only draft payroll can be edited");const updated=(await client.query("UPDATE payroll_payslips SET allowances=$3,deductions=$4,notes=$5,updated_at=now() WHERE id=$1 AND payroll_run_id=$2 RETURNING *",[req.params.id,req.params.runId,i.allowances,i.deductions,i.notes])).rows[0];if(!updated)throw new HttpError(404,"PAYSLIP_NOT_FOUND","Payslip not found");await recalculate(client,String(req.params.runId));return updated;});res.json({data:serializeRow(row)});});
payrollRouter.post("/runs/:id/approve",approve,async(req,res)=>{const row=await transaction(async client=>{const before=(await client.query("SELECT * FROM payroll_runs WHERE id=$1 AND company_id=$2 FOR UPDATE",[req.params.id,req.auth!.companyId])).rows[0];if(!before)throw new HttpError(404,"PAYROLL_RUN_NOT_FOUND","Payroll run not found");if(before.status!=="draft")throw new HttpError(409,"INVALID_PAYROLL_STATUS","Only draft payroll can be approved");const updated=(await client.query("UPDATE payroll_runs SET status='approved',approved_by=$2,approved_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[req.params.id,req.auth!.userId])).rows[0];await appendAuditEvent(client,{tenantId:req.auth!.tenantId,companyId:req.auth!.companyId,actorUserId:req.auth!.userId,action:"payroll.run_approved",entityType:"payroll_run",entityId:String(req.params.id),before,after:updated});return updated;});res.json({data:serializeRow(row)});});
payrollRouter.post("/runs/:id/pay",approve,async(req,res)=>{const i=validate(z.object({accountId:z.uuid()}),req.body);const row=await transaction(async client=>{const run=(await client.query("SELECT * FROM payroll_runs WHERE id=$1 AND company_id=$2 FOR UPDATE",[req.params.id,req.auth!.companyId])).rows[0];if(!run)throw new HttpError(404,"PAYROLL_RUN_NOT_FOUND","Payroll run not found");if(run.status!=="approved")throw new HttpError(409,"INVALID_PAYROLL_STATUS","Only approved payroll can be paid");const account=(await client.query("SELECT * FROM financial_accounts WHERE id=$1 AND company_id=$2 AND is_active=true FOR UPDATE",[i.accountId,req.auth!.companyId])).rows[0];if(!account)throw new HttpError(400,"INVALID_PAYMENT_ACCOUNT","Payment account is invalid");await client.query("INSERT INTO financial_movements(company_id,account_id,movement_type,amount,business_date,description,source_type,source_id,operation_key,created_by)VALUES($1,$2,'payroll',-$3,current_date,$4,'payroll_run',$5,$6,$7)",[req.auth!.companyId,i.accountId,run.total_net,`Payroll ${run.year}-${String(run.month).padStart(2,"0")}`,run.id,`payroll:${run.id}`,req.auth!.userId]);await client.query("UPDATE financial_accounts SET balance=balance-$2 WHERE id=$1",[i.accountId,run.total_net]);const updated=(await client.query("UPDATE payroll_runs SET status='paid',paid_by=$2,paid_at=now(),payment_account_id=$3,updated_at=now() WHERE id=$1 RETURNING *",[run.id,req.auth!.userId,i.accountId])).rows[0];await appendAuditEvent(client,{tenantId:req.auth!.tenantId,companyId:req.auth!.companyId,actorUserId:req.auth!.userId,action:"payroll.run_paid",entityType:"payroll_run",entityId:run.id,before:run,after:updated});return updated;});res.json({data:serializeRow(row)});});
